In [2]:
import pandas as pd
train_df = pd.read_csv("fraudTrain.csv")
test_df = pd.read_csv("fraudTest.csv")

In [3]:
train_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [4]:
test_df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [6]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

In [7]:
drop_cols = [
    'Unnamed: 0',
    'trans_date_trans_time',
    'cc_num']
train_df = train_df.drop(columns=drop_cols)
test_df = test_df.drop(columns=drop_cols)

In [8]:
drop_cols = [
    'first', 'last',
    'street', 'city', 'state', 'zip',
    'dob',
    'trans_num'
]

train_df = train_df.drop(columns=drop_cols)
test_df = test_df.drop(columns=drop_cols)

In [9]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 12 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   merchant    1296675 non-null  object
 1   category    1296675 non-null  object
 2   amt         1296675 non-null  float64
 3   gender      1296675 non-null  object
 4   lat         1296675 non-null  float64
 5   long        1296675 non-null  float64
 6   city_pop    1296675 non-null  int64
 7   job         1296675 non-null  object
 8   unix_time   1296675 non-null  int64
 9   merch_lat   1296675 non-null  float64
 10  merch_long  1296675 non-null  float64
 11  is_fraud    1296675 non-null  int64
dtypes: float64(5), int64(3), object(4)
memory usage: 118.7+ MB

In [10]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   merchant    555719 non-null  object
 1   category    555719 non-null  object
 2   amt         555719 non-null  float64
 3   gender      555719 non-null  object
 4   lat         555719 non-null  float64
 5   long        555719 non-null  float64
 6   city_pop    555719 non-null  int64
 7   job         555719 non-null  object
 8   unix_time   555719 non-null  int64
 9   merch_lat   555719 non-null  float64
 10  merch_long  555719 non-null  float64
 11  is_fraud    555719 non-null  int64
dtypes: float64(5), int64(3), object(4)
memory usage: 50.9+ MB

In [11]:
train_df.isnull().sum()

merchant      0
category      0
amt           0
gender        0
lat           0
long          0
city_pop      0
job           0
unix_time     0
merch_lat     0
merch_long    0
is_fraud      0
dtype: int64

In [12]:
test_df.isnull().sum()

merchant      0
category      0
amt           0
gender        0
lat           0
long          0
city_pop      0
job           0
unix_time     0
merch_lat     0
merch_long    0
is_fraud      0
dtype: int64

In [13]:
train_df = pd.get_dummies(train_df, drop_first=True)

In [14]:
test_df = pd.get_dummies(test_df, drop_first=True)

In [15]:
train_df

,amt,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,merchant_fraud_Abbott-Steuber,merchant_fraud_Abernathy and Sons,...,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Warehouse manager,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
0,4.97,36.0788,-81.1781,3495,1325376018,36.011293,-82.048315,0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,107.23,48.8878,-118.2105,149,1325376044,49.159047,-118.186462,0,False,False,...,False,False,False,False,False,False,False,False,False,False
2,220.11,42.1808,-112.2620,4154,1325376051,43.150704,-112.154481,0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,45.00,46.2306,-112.1138,1939,1325376076,47.034331,-112.561071,0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,41.96,38.4207,-79.4629,99,1325376186,38.674999,-78.632459,0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,15.56,37.7175,-112.4777,258,1371816728,36.841266,-111.690765,0,False,False,...,False,False,False,False,False,False,False,False,False,False
1296671,51.70,39.2667,-77.5101,100,1371816739,38.906881,-78.246528,0,False,True,...,False,False,False,False,False,False,False,False,False,False
1296672,105.93,32.9396,-105.8189,899,1371816752,33.619513,-105.130529,0,False,False,...,False,False,False,False,False,False,False,False,False,False
1296673,74.90,43.3526,-102.5411,1126,1371816816,42.788940,-103.241160,0,False,False,...,False,True,False,False,False,False,False,False,False,False
1296674,4.30,45.8433,-113.8748,218,1371816817,46.565983,-114.186110,0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
test_df

,amt,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud,merchant_fraud_Abbott-Steuber,merchant_fraud_Abernathy and Sons,...,job_Video editor,job_Visual merchandiser,job_Volunteer coordinator,job_Warden/ranger,job_Waste management officer,job_Water engineer,job_Water quality scientist,job_Web designer,job_Wellsite geologist,job_Writer
0,2.86,33.9659,-80.9355,333497,1371816865,33.986391,-81.200714,0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,29.84,40.3207,-110.4360,302,1371816873,39.450498,-109.960431,0,False,False,...,False,False,False,False,False,False,False,False,False,False
2,41.28,40.6729,-73.5365,34496,1371816893,40.495810,-74.196111,0,False,False,...,False,False,False,False,False,False,False,False,False,False
3,60.05,28.5697,-80.8191,54767,1371816915,28.812398,-80.883061,0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,3.19,44.2529,-85.0170,1126,1371816917,44.959148,-85.884734,0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,43.77,40.4931,-91.8912,519,1388534347,39.946837,-91.333331,0,False,False,...,False,False,False,False,False,False,False,False,False,False
555715,111.84,29.0393,-95.4401,28739,1388534349,29.661049,-96.186633,0,False,False,...,False,False,False,False,False,False,False,False,False,False
555716,86.88,46.1966,-118.9017,3684,1388534355,46.658340,-119.715054,0,False,False,...,False,False,False,False,False,False,False,False,False,False
555717,7.99,44.6255,-116.4493,129,1388534364,44.470525,-117.080888,0,False,False,...,False,False,False,False,False,False,False,False,False,False
555718,38.13,35.6665,-97.4798,116001,1388534374,36.210097,-97.036372,0,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
train_df, test_df = train_df.align(test_df, join='left', axis=1, fill_value=0)

In [18]:
train_df = train_df.sample(10000, random_state=42)
test_df = test_df.sample(80000, random_state=42) #used this bex my dataset was having a large data

In [19]:
X_train = train_df.drop('is_fraud', axis=1)
y_train = train_df['is_fraud']

In [20]:
X_test = test_df.drop('is_fraud', axis=1)
y_test = test_df['is_fraud']

In [21]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000, class_weight='balanced')

In [30]:
lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [31]:
from sklearn.metrics import accuracy_score
y_pred_lr = lr.predict(X_test)
print("accuracy_score",accuracy_score(y_test,y_pred_lr))

accuracy_score 0.9336875

In [32]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_lr))
print(confusion_matrix(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       1.00      0.93      0.97     79697
           1       0.04      0.80      0.08       303

    accuracy                           0.93     80000
   macro avg       0.52      0.87      0.52     80000
weighted avg       1.00      0.93      0.96     80000

[[74453  5244]
 [   61   242]]

In [26]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(class_weight='balanced', random_state=42)

In [27]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [28]:
from sklearn.metrics import accuracy_score
y_pred_rf = rf.predict(X_test)
print("accuracy_score",accuracy_score(y_test,y_pred_rf))

accuracy_score 0.9962125

In [29]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     79697
           1       0.00      0.00      0.00       303

    accuracy                           1.00     80000
   macro avg       0.50      0.50      0.50     80000
weighted avg       0.99      1.00      0.99     80000

[[79697     0]
 [  303     0]]

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))